# Enum constants for the submission required to complete a task
TASK_READ_ONLY = 0
TASK_FILE_SUBMISSION = 1
MAX_TASK_TYPE = TASK_FILE_SUBMISSION

# Task Categories
CATEGORY_GENERAL = 0
CATEGORY_FOR_FUN = 1
MAX_CATEGORY = CATEGORY_FOR_FUN

# Task Statuses
STATUS_UNAVAILABLE = 0
STATUS_AVAILABLE = 1
STATUS_SUBMITTED = 2
STATUS_COMPLETED = 3

ALLOWED_IMAGE_EXTENSIONS = ["jpg", "png", "jpeg", "gif"]